---
name: Checks

on: [push]

jobs:
  ## below is the id that can be refered in some other place in the git-hub actions
  test-lint:
    name: Test and Lint
    ## BELOW IS THE OS WHERE GONNA RUN DOCKER
    runs-on: ubuntu-20.04
    ## steps of the job
    steps:
      ##HUMAN READLE NAME FOR THIS STEPS
      - name: Login to Docker Hub
        ##REUSE THIS ACTION THAT IS COMING FROM THE DOCKER ACTION THAT PERFORM THE LOGIN THAT IS VERSION 1
        uses: docker/login-action@v1
        with:
          ## USING THIS CREDENTIALS
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test" ## add the wait_db bcs the db should be ready before the test 
      - name: Lint
        run : docker-compose run --rm app sh -c "flake8"
